// <auto-generated>
// tools/build_package.py tarafindan tools/sprite_specs.json'dan uretildi; elle duzenlemeyin.
// Kur komutu kit gorsellerinin ice aktarma ayarlarini bu tabloya gore denetler (CNEUIKitAssets).
// </auto-generated>
using UnityEngine;

namespace CookNoEvil.UI.EditorTools
{
    static class CNEUIKitSpriteSpecs
    {
        public sealed class Spec
        {
            public readonly string path;
            /// <summary>9-dilim kenarlari (piksel): x sol, y alt, z sag, w ust.</summary>
            public readonly Vector4 border;
            public readonly Vector2 pivot;
            public readonly float ppu;
            public readonly bool cursor, repeat, compressed;

            public Spec(string path, float left, float bottom, float right, float top, float pivotX, float pivotY,
                float ppu, bool cursor, bool repeat, bool compressed)
            {
                this.path = path;
                border = new Vector4(left, bottom, right, top);
                pivot = new Vector2(pivotX, pivotY);
                this.ppu = ppu;
                this.cursor = cursor;
                this.repeat = repeat;
                this.compressed = compressed;
            }

            public bool CustomPivot
            {
                get { return Mathf.Abs(pivot.x - 0.5f) > 0.0001f || Mathf.Abs(pivot.y - 0.5f) > 0.0001f; }
            }
        }

        public static readonly Spec[] All =
        {
            new Spec("Assets/CNE_UI/Art/Kit/ui_shape_r16.png", 40f, 40f, 40f, 40f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_shape_r28.png", 64f, 64f, 64f, 64f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_outline_r16.png", 40f, 40f, 40f, 40f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_outline_r28.png", 64f, 64f, 64f, 64f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_bevel_r16.png", 40f, 40f, 40f, 40f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_ring_r16.png", 40f, 40f, 40f, 40f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_panel_formika.png", 88f, 88f, 88f, 88f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_sign_plate.png", 40f, 40f, 40f, 40f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_board_tile.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, true, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_frame_chrome.png", 72f, 72f, 72f, 72f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_arrow.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_glow.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_white.png", 2f, 2f, 2f, 2f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_slider_rail.png", 30f, 15f, 30f, 15f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_slider_fill.png", 14f, 11f, 14f, 11f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_knob.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_switch_housing.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_switch_paddle.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_led.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_rotary_knob.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_tick.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_vu_face.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_vu_needle.png", 0f, 0f, 0f, 0f, 0.5f, 0.059211f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_record.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Kit/ui_jukebox_strip.png", 24f, 24f, 24f, 24f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Misc/cursor_kurdan.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 100f, true, false, false),
            new Spec("Assets/CNE_UI/Art/Misc/bg_menu_demo.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 100f, false, false, true),
            new Spec("Assets/CNE_UI/Art/Flags/flag_tr.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Flags/flag_us.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
            new Spec("Assets/CNE_UI/Art/Flags/flag_gb.png", 0f, 0f, 0f, 0f, 0.5f, 0.5f, 200f, false, false, false),
        };
    }
}
